    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    panda_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7
        gains:
            panda_joint1: {p: 1000, d: 100, i: 0.01}
            panda_joint2: {p: 1000, d: 100, i: 0.01}
            panda_joint3: {p: 1000, d: 100, i: 0.01}
            panda_joint4: {p: 1000, d: 100, i: 0.01}
            panda_joint5: {p: 1000, d: 100, i: 0.01}
            panda_joint6: {p: 1000, d: 100, i: 0.01}
            panda_joint7: {p: 1000, d: 100, i: 0.01}

        constraints:
            goal_time: 2.0

        state_publish_rate: 100

    panda_hand_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_finger_joint1
            - panda_finger_joint2
        gains:
            panda_finger_joint1: {p: 100, d: 10, i: 0.01}
            panda_finger_joint2: {p: 100, d: 10, i: 0.01}

        state_publish_rate: 25
    joint_position_controller:
        type: panda_simulation/JointPositionController
        arm_id: panda
        joint_names:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7
        gains: [
            1, 1, 1, 1, 1, 1, 1
        ]
